dingtalk:
  auto_check_in:
    enable: true # 开启自动签到
    delay_time: 5 # 自动签到间隔时间（单位：秒）
  auto_class:
    enable: true # 开启 自动上课 & 自动下课
    check_open_delay_time: 60 # 检测直播是否开启的间隔时间（单位：秒）
    check_end_delay_time: 5 # 检测直播是否关闭的间隔时间（单位：秒）
  get_latest_version: true  # 检测最新版本