name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Setup requirements
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build LDingTalk
        run: pyinstaller -F main.py

      - name: Rename
        run: mv dist/main.exe LDingTalk.exe

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: LDingTalk
          path: LDingTalk.exe